# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode7.2
r:
  - release
  - devel
  - oldrel
sudo: false
cache: packages
warnings_are_errors: true